const nav = document.querySelector(".nav"),
  searchIcon = document.querySelector("#searchIcon"),
  navOpenBtn = document.querySelector(".navOpenBtn"),
  navCloseBtn = document.querySelector(".navCloseBtn");

searchIcon.addEventListener("click", () => {
  nav.classList.toggle("openSearch");
  nav.classList.remove("openNav");
  if (nav.classList.contains("openSearch")) {
    return searchIcon.classList.replace("uil-search", "uil-times");
  }
  searchIcon.classList.replace("uil-times", "uil-search");
});

navOpenBtn.addEventListener("click", () => {
  nav.classList.add("openNav");
  nav.classList.remove("openSearch");
  searchIcon.classList.replace("uil-times", "uil-search");
});
navCloseBtn.addEventListener("click", () => {
  nav.classList.remove("openNav");
});

//CHANGE STYLE TRUE OR FALSE FOR SWITCH BETWEEN STYLES
Vue.createApp({
  data() {
    return {
      animItems: [
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: true,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: true,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: true,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: true,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: true,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: true,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: true,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: true,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: true,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: true,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: true,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: true,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: true,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: true,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: true,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: true,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: true,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: true,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: true,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: true,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: true,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: true,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: true,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: false,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
        {
          Name: "Animation 1",
          link: "https://gradientbuttons.colorion.co/",
          setStyle1: false,
          setStyle2: true,
          setStyle3: false,
          setStyle4: false,
          setStyle5: false,
          default: true,
        },
      ],
    };
  },
}).mount("body");
